-- Terminal App (Lua)
clear_screen()
set_color("black")
draw_rect(0, 0, 640, 480, "true")
set_color("white")
draw_text_at("> FerroOS Terminal v1.0", 10, 10)
draw_text_at("> Usuario: DevMaubry", 10, 30)
draw_text_at("> $ help", 10, 50)
draw_text_at("  Comandos disponibles:", 10, 70)
draw_text_at("  - help: Muestra esta ayuda", 10, 90)
draw_text_at("  - clear: Limpia la pantalla", 10, 110)
draw_text_at("  - exit: Salir de la terminal", 10, 130)
draw_text_at("  (Esta es una demo visual)", 10, 160)
draw_text_at("> $ _", 10, 190)
